FROM python:3.10
RUN apt-get update && apt-get install -y --no-install-recommends libc++1 libc++abi1 && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir numpy==1.26.4 onnx==1.18.0 onnxruntime onnxsim pyyaml packaging
WORKDIR /workspace
